version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: uts_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: uts_db
    ports:
      - "3306:3306"

  postgres:
    image: postgres:15
    container_name: uts_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: uts_db
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    container_name: uts_adminer
    ports:
      - "8080:8080"
