version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: uts_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_uts
      MYSQL_DATABASE: uts_mysql_db
      MYSQL_USER: uts_user
      MYSQL_PASSWORD: uts_password
    ports:
      - "3306:3306"

  postgres:
    image: postgres:15
    container_name: uts_postgres
    environment:
      POSTGRES_DB: uts_postgres_db
      POSTGRES_USER: uts_user
      POSTGRES_PASSWORD: uts_password
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    container_name: uts_adminer
    ports:
      - "8080:8080"
